name: Build AMI
on:
  push:
    branches: [ "dev" ]

env:
  AWS_REGION: ap-south-1        # set this to your preferred AWS region, e.g. us-west-1
  
jobs:
  build-ami:
    uses: Algorizz/infra-as-code/.github/workflows/build-ami-central.yml@main
    with:
      microservice: NCERT-IoT-Backend
      branch_name: ${{ github.ref_name }}
      env: dev
      project: NCERT-IoT-Backend
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy-infra:
    needs: build-ami
    uses: Algorizz/infra-as-code/.github/workflows/deploy-infra.yml@main
    with:
      microservice: NCERT-IoT-Backend
      branch_name: ${{ github.ref_name }}
      env: dev
      project: NCERT-IoT-Backend
      s3_bucket: ncert-backend
      terraform_command: apply 
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
